### ISSUE TITLE
Rectangle unwanted resizing

### ISSUE THREAD

**Issue by kothemel** [nandi95/vue-toastify#11]
Hi!,

It seems that if the body message is made of 17 characters and you set a timeout on the popup window, at the final second the rectangle resizes itself and it puts the icon at the bottom of the message window.

You can try it at [netlify](https://vue-toastify.netlify.com/) by writing a body "Hellooooooooooooo". You can replicate if the title is made of 11 characters.

**Comment by nandi95** [comment]
Fixed in version `1.5.2`

**Comment by kothemel** [comment]
The issue remains and it's not completely solved.
Try a body of 17 characters or a title of 15 characters.
